#spring配置
spring:
  #数据库连接池
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/carbon?useUnicode=true&characterEncoding=utf8
      username: root
      password: 1234
      initial-size: 5 # 下面为连接池的补充设置，应用到上面所有数据源中# 初始化大小，最小，最大
      min-idle: 5
      max-active: 200
      max-wait: 120000 # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 28000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      #min-evictable-idle-time-millis: 18000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      #max-evictable-idle-time-millis: 60000
      validation-query: SELECT 1
      #validation-query-timeout: 3000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true # 打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1234
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848

  #分布式锁配置
#  spring:
#    klock:
#      address: r-uf6f430a98d6db74.redis.rds.aliyuncs.com
#      password: ALi415523
#      database: 0

chain:
  timeout:
    rpc: 20000
    sync: 6000
    block: 10000
