#服务配置
server:
  port: 9003
  servlet:
    context-path: /assets

#spring配置
spring:
  application:
    name: carbon-assets #指定服务名
  profiles:
    # 本地运行使用dev，打包时使用test
#    active: dev
    active: dev
  servlet: # 此版本的节点为servlet，不是http 注意一下
    multipart:
      enabled: true # 启用上传处理，默认是true
      file-size-threshold: 10MB   # 当上传文件达到10MB的时候进行磁盘写入
      max-request-size: 10MB    # 设置最大的请求文件的大小
      max-file-size: 10MB    # 设置单个文件的最大长度

  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: ALWAYS
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true

# 设置 feign 超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
