#服务配置
server:
  port: 9006
  servlet:
    context-path: /mq

#spring配置
spring:
  application:
    name: carbon-mq #指定服务名
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: ALWAYS
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true

# 设置 feign 超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

